[env]
SMARTSHEET_ACCESS_TOKEN = ""

[tables.TF-FXA]
id = ""
src = "TF-FXA.xlsx"

[tables.TF-FXE]
id = ""
src = "TF-FXE.xlsx"

[tables.TF-FXG]
id = ""
src = "TF-FXG.xlsx"

[tables.TF-FXH]
id = ""
src = "TF-FXH.xlsx"

[tables.TF-FXI]
id = ""
src = "TF-FXI.xlsx"

[tables.TF-FXK]
id = ""
src = "TF-FXK.xlsx"
